# -*- coding: utf-8 -*-
"""blackscholes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aCZEl8B1WpyYmGuBC9YvHUAAazm0NIDl

Model
"""

import tensorflow as tf
import matplotlib.pyplot as plt


nodes = 200
model = tf.keras.models.Sequential([
	# Layer 1
	tf.keras.layers.Input(dtype=float,shape=(6,)),
	
	tf.keras.layers.Dense(nodes, input_shape=(6,)) ,
	tf.keras.layers.Activation('relu'),
	tf.keras.layers.Dropout(0.25),
	# Layer 2
	tf.keras.layers.Dense(nodes),
	tf.keras.layers.Activation ('relu'),
	tf.keras.layers.Dropout(0.25),
	# Layer 3
	tf.keras.layers.Dense(nodes),
	tf.keras.layers.Activation ('relu'),
	tf.keras.layers.Dropout(0.25),
	# Layer 4
	#tf.keras.layers.Dense(nodes),
	#tf.keras.layers.Activation ('relu'),
	#tf.keras.layers.Dropout(0.25),
	# Layer 4
	#tf.keras.layers.Dense(nodes),
	#tf.keras.layers.Activation ('relu'),
	#tf.keras.layers.Dropout(0.25),
	# Layer 5 - Output Layer
	tf.keras.layers.Dense(1),
	tf.keras.layers.Activation('elu')
])

model.compile(optimizer='RMSprop', loss=tf.keras.metrics.mean_squared_error, metrics=["mae"])


model.summary()

inTrain = []
outTrain = []
inTest = []
outTest = []

f = open("aggregated.fann", "r")
shape = f.readline()
num=int(shape.split()[0])
numTrain = int(num*0.9)
numTest = int(num*0.1)

for i in range(numTrain):
  inLine = f.readline()
  outLine = f.readline()
  if not inLine or not outLine:
    break
  inStr = inLine.split()
  inFloat = []
  inFloat.append(float(inStr[0]))
  inFloat.append(float(inStr[1]))
  inFloat.append(float(inStr[2]))
  inFloat.append(float(inStr[3]))
  inFloat.append(float(inStr[4]))
  inFloat.append(float(inStr[5]))
  inTrain.append(inFloat)
  outTrain.append(float(outLine))

for i in range(numTest):
  inLine = f.readline()
  outLine = f.readline()
  if not inLine or not outLine:
    break
  inStr = inLine.split()
  inFloat = []
  inFloat.append(float(inStr[0]))
  inFloat.append(float(inStr[1]))
  inFloat.append(float(inStr[2]))
  inFloat.append(float(inStr[3]))
  inFloat.append(float(inStr[4]))
  inFloat.append(float(inStr[5]))
  inTest.append(inFloat)
  outTest.append(float(outLine))

f.close()

"""Train model"""

model.fit(inTrain, outTrain, epochs=100)

"""Evaluate"""

ev = model.evaluate(inTest, outTest, verbose=1)
#print("Maes:", ev[1])

#predictions = model.predict(inTest)
#plt.figure(figsize = (15,10))
#plt.scatter(outTest, predictions)
#plt.xlabel("Actual Price")
#plt.ylabel("Predicted Price")
#plt.plot([0,0.2], [0,0.2], 'r')
#plt.grid(True)
#plt.show()

for i in range(numTest):
	test=[]
	test.append(inTest[i])
	#print(model.predict(test),outTest[i])

model.save('model')

def representative_dataset():
  for data in tf.data.Dataset.from_tensor_slices((inTrain)).batch(1).take(100):
    yield [data]

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
#converter.inference_input_type = tf.int8
#converter.inference_output_type = tf.int8
tflite_model = converter.convert()

with open('model.tflite', 'wb') as f:
  f.write(tflite_model)










